# -*- coding: utf-8 -*-
"""Hate Speech Detection Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXqVspQRM3lHBlnj10SaMAH6AmASJrcS

# Import Required Libraries
"""

import pandas as pd
import numpy as np
import re
import string
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

"""# Load Dataset"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("labeled_data.csv")  # replace with your actual file name
df.head()

"""# Check and Map Labels"""

# Optional: Rename columns if needed
df.rename(columns={"class": "label", "tweet": "text"}, inplace=True)

# Map class numbers to text (0=hate, 1=offensive, 2=neutral)
label_map = {0: "Hate Speech", 1: "Offensive", 2: "Neutral"}
df["label_text"] = df["label"].map(label_map)

df["label_text"].value_counts()

df.head()

df.isnull().sum()

df.duplicated(subset='text').sum()

"""# Understanding the distribution of the numerical columns"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plotting the histogram
sns.histplot(df[['count', 'hate_speech', 'offensive_language', 'neither', 'label']], bins=30, kde=True)
plt.title("Distribution of Numerical Column")
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.show()

"""# Clearing and removing the unnecessary characters and words in the tweet"""

import regex as re
import string
import nltk # Import the nltk library
from nltk.corpus import stopwords # Import the stopwords module

# Download stopwords if not already downloaded
nltk.download('stopwords')

def preprocess_text(text):
    text = text.lower()  # Converting the tweet in to lowercase
    text = re.sub(r'http\S+', '', text)  # Removing any URLs
    text = re.sub(r'@\w+', '', text)  # Removing any mentions
    text = re.sub(f"[{string.punctuation}]", '', text)  # Removing any punctuation
    text = re.sub(r'\d+', '', text)  # Removing the numerals
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Removing the stopwords or otherwise commonly used words (i.e.and, you, him, etc.)
    return text

df['processed_tweet'] = df['text'].apply(preprocess_text)
df['processed_tweet'].head()

"""# Vectorize the Clean Text"""

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
# Use 'processed_tweet' instead of 'clean_text'
X = vectorizer.fit_transform(df["processed_tweet"])
y = df["label"]

"""# Train-Test Split"""

from sklearn.model_selection import train_test_split

# Use 'processed_tweet' instead of 'tweet' to access the preprocessed text data
x = df['processed_tweet']
y = df['label']  # Assuming 'label' contains the target variable (0, 1, 2)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4)

"""# Encoding the words"""

vectorizer = TfidfVectorizer(max_features=5000)  # Maximum number of features the words will be put into
x_train_tfidf = vectorizer.fit_transform(x_train)
x_test_tfidf = vectorizer.transform(x_test)

"""# Graph visualizing the frequency of words in the total conversation"""

from collections import Counter
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')
nltk.download('punkt')

# Combine all tweets into one list of words
all_words = [word.lower() for tweet in df['processed_tweet'].dropna() for word in word_tokenize(tweet)]

# Get the most common words
word_freq = Counter(all_words)
common_words = word_freq.most_common(20)
words, counts = zip(*common_words)

# Bar plot of word frequencies
plt.figure(figsize=(12, 6))
sns.barplot(x=list(words), y=list(counts), palette='viridis')
plt.title("Top 20 Most Common Words")
plt.xticks(rotation=45)
plt.ylabel("Frequency")
plt.xlabel("Words")
plt.show()

"""# Graph visualizing the words with highest frequencies for each"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
import string

# Download required NLTK data
nltk.download('punkt')
nltk.download('stopwords')

# Define stop words
stop_words = set(stopwords.words('english'))

# Step 1: Separate tweets into classes
# Use 'label' instead of 'class' to access the correct column
hate_speech_tweets = df[df['label'] == 0]['processed_tweet'].dropna()
offensive_language_tweets = df[df['label'] == 1]['processed_tweet'].dropna()
neither_tweets = df[df['label'] == 2]['processed_tweet'].dropna()

# Step 2: Tokenize, filter, and count word frequencies
def get_word_frequencies(tweets):
    all_words = [
        word.lower() for tweet in tweets for word in word_tokenize(tweet)
        if word.isalpha() and word.lower() not in stop_words  # Exclude stopwords and keep only alphabetic words
    ]
    word_freq = Counter(all_words)
    return word_freq.most_common(10)  # Top 10 words

hate_speech_freq = get_word_frequencies(hate_speech_tweets)
offensive_language_freq = get_word_frequencies(offensive_language_tweets)
neither_freq = get_word_frequencies(neither_tweets)

# Step 3: Prepare DataFrame for visualization
freq_data = pd.DataFrame({
    'Hate Speech': dict(hate_speech_freq),
    'Offensive Language': dict(offensive_language_freq),
    'Neither': dict(neither_freq)
}).fillna(0)

# Reshape the data for a grouped bar chart
freq_data = freq_data.stack().reset_index()
freq_data.columns = ['Word', 'Class', 'Frequency']

# Step 4: Plot the grouped bar chart
plt.figure(figsize=(15, 8))
sns.barplot(data=freq_data, x='Word', y='Frequency', hue='Class', palette='coolwarm')
plt.title("Top Words in Each Class by Frequency (Filtered with Stopword Removal)")
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.legend(title="Class")
plt.show()

"""# Train Logistic Regression Model"""

model = LogisticRegression()
model.fit(x_train_tfidf, y_train) # Use x_train_tfidf instead of X_train

"""# Evaluate the Model"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train the logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(x_train_tfidf, y_train) # Replace train_labels with y_train

# Predict on the test data
y_pred = model.predict(x_test_tfidf)

# Use y_pred instead of y_predict
Accuracy = accuracy_score(y_test, y_pred)
Conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {Accuracy}")

# Print classification report
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=["Hate", "Offensive", "Neutral"]))

# Generate and plot the confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, cmap='Blues', fmt='d',
            xticklabels=["Hate", "Offensive", "Neutral"],
            yticklabels=["Hate", "Offensive", "Neutral"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

"""# BERT MODEL

Tokenizing and Encoding the dataset to prepare to train the birt model
"""

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize_data(texts, labels, tokenizer, max_len=128):
    encodings = tokenizer(
        list(texts),
        truncation=True,
        padding=True,
        max_length=max_len,
        return_tensors="pt"
    )
    return encodings, labels

train_encodings, train_labels = tokenize_data(x_train, y_train, tokenizer)
test_encodings, test_labels = tokenize_data(x_test, y_test, tokenizer)

"""Preparing the dataset to use for the bert model trainging"""

import torch
from torch.utils.data import Dataset

class TweetDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx])
        return item
#Packaging the dataset for the model
train_dataset = TweetDataset(train_encodings, train_labels)
test_dataset = TweetDataset(test_encodings, test_labels)

"""Loading the BERT Model"""

from transformers import BertForSequenceClassification

#Loading the pre trained Bert Model
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3 # for classes hate speech, offensive language and neither
)

"""Initializing the Bert model"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import AdamW
from transformers import get_scheduler

#import torch_xla.core.xla_model as xm

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

# Optimizer and Scheduler
optimizer = AdamW(model.parameters(), lr=5e-5)
num_training_steps = len(train_loader) * 3  # 3 epochs
lr_scheduler = get_scheduler("linear", optimizer=optimizer, num_warmup_steps=0, num_training_steps=num_training_steps)

# Set device
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

if torch.cuda.device_count() > 1:
    print(f"Using {torch.cuda.device_count()} GPUs!")
    model = nn.DataParallel(model)

#device = xm.xla_device()
model.to(device)

# Save model
torch.save(model.state_dict(), 'bert_hate_speech_model.pt')

# Load model (later)
model.load_state_dict(torch.load('bert_hate_speech_model.pt'))

"""Training the bert model"""

from tqdm import tqdm

# Training Loop
epochs = 3
progress_bar = tqdm(range(num_training_steps))

model.train()
for epoch in range(epochs):
    for batch in train_loader:
        batch = {key: val.to(device) for key, val in batch.items()}
        outputs = model(**batch)

        # Ensure the loss is reduced to a scalar
        loss = outputs.loss
        if loss.dim() > 0:  # If loss is not scalar
            loss = loss.mean()  # Reduce to a scalar

        # Backpropagation
        loss.backward()

        # Optimizer step and scheduler
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()

        # Update progress bar
        progress_bar.update(1)

print("Training complete.")

"""Evaluating the bert model"""

import torch
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Set model to evaluation mode
model.eval()

# Initialize lists to store predictions and true labels
predictions = []
true_labels = []

# No gradient calculation needed for evaluation
with torch.no_grad():
    for batch in test_loader:
        batch = {key: val.to(device) for key, val in batch.items()}
        outputs = model(**batch)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=1).cpu().numpy()
        labels = batch['labels'].cpu().numpy()

        predictions.extend(preds)
        true_labels.extend(labels)

# Compute accuracy
accuracy = accuracy_score(true_labels, predictions)

# Classification report
class_report = classification_report(true_labels, predictions, target_names=["Hate", "Offensive", "Neutral"])

# Confusion matrix
cm = confusion_matrix(true_labels, predictions)

# Print results
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", class_report)

# Plot confusion matrix with seaborn heatmap
sns.heatmap(cm, annot=True, cmap='Blues', fmt='d',
            xticklabels=["Hate", "Offensive", "Neutral"],
            yticklabels=["Hate", "Offensive", "Neutral"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

"""# Predict on New Inputs"""

def predict_text(text):
    # Use the defined function 'preprocess_text' instead of 'preprocess'
    clean = preprocess_text(text)
    # Tokenize the input text
    inputs = tokenizer(clean, return_tensors="pt", padding=True, truncation=True).to(device)

    # Get model predictions (logits)
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits

    # Get the predicted class
    pred = torch.argmax(logits, dim=1).item()  # Get the class index

    return label_map[pred]

# Test example
print(predict_text("I hate you!"))
print(predict_text("You're so kind and thoughtful."))